on: pull_request
name: Test
jobs:
  tests:
    name: Running the tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != true
        run: npm ci
      - name: Execute the tests
        run: npm test