on:
  push:
    branches:
      - master
name: Deploy Home to Firebase
env:
  NODE_ENV: production
jobs:
  deploy:
    name: Deploy Home
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != true
        run: npm ci 
      - name: Build Home
        run: npm run build
      - name: Deploy
        run: npm install -g firebase-tools && firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
